version: "3"
services:
    sqlserver:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStrongPassword12#
        ports:
            - 1433:1433
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - taskboard_network
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
    taskboard:
        ports:
            - 5000:80
        container_name: web_app
        networks:
            - taskboard_network
        # image: taskboard
        build: 
          dockerfile: .\TaskBoard.WebApp\Dockerfile
networks:
    taskboard_network:
        external: true
      
volumes:
    sqldata:
        external: true



